### PR TITLE
New Features added to linters branch 

### PR DESCRIPTION
**Pull request by Benawi**
linters added to the repo

### CODE REVIEW

**Review by Zuhaib042 — COMMENTED** [review]
Hi @Benawi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not following the Github flow. according to Github flow, you should make a pull request from a feature branch into main or master branch of your repo. and all the required changes and requirements should be on the feature branch so that a reviewer can review it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by shella12 — CHANGES_REQUESTED** [review]
Hi @Benawi , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- All linters passed ✅ 
- Use README.md Template ✅   

## Required Changes ♻️

- [ ] Please make sure to implement following:

      - [ ] - There are 2 files committed: an `.html `and `.css `file. 
      - [ ] -There is a `.gitignore` file listing `test.md `file and `node_modules` directory

- [ ] Great job on using the Microverse template for your README.md however please make sure to customize this template by adding descriptions to each section, reflecting your project. Also make sure totake care of the following:

       - Please remove Note from the LICENCE section of the README. Note is there in the template to guide you on how you to add a LICENCE to your README. Once you have successfully added the LICENCE you can go ahead and remove it
       - The link to your `MIT LICENCE` is broken. Please use these [guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to correctly add LICENCE into your README.
       - Please remove the Microverse logo from your readme. Optionally, you can replace with your own logo if you want.
       -  Please remove the default comment like
       
            > Give credit to everyone who inspired your codebase.  
           > Write a message to encourage readers to support your project  
           > Describe 1 - 3 features you will add to the project.  
          
          ,etc from your README. 
          They were used in the template to explain to the user the purpose of each section. You can go ahead and remove it from your README

- [ ] Please make sure to folow the create `gitflow`i.e. Pull Request (PR) is made from the `“feature branch”` (in your case `linters`)into the `main branch`. You can change the base branch using this Github doc -> [Changing the base branch of a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Benawi** [comment]
Dear all,
Thank you for great review comment ,
I am trying to creat new repo but unable to submit the new repo link to you through the dashboard. 
The following points are the procedures I did to my project.
Every time while  I push to a branch that is tied to a merge request, a new version of merge request is created.
Basicaly I have 4 branches(Main, feature-1(for Index), feature-css(for CSS file), and  linter branch(for Styleint) I did the following  Merging flow Main<-feature-css<-feature-1(Index)<-linter branch(Styleint)
Now I am requesting to merge  : Main<-feature-css(Which is merged with feature-1(for Index)- Merged with linter branch(for Styleint) 
here is it the link:  https://github.com/Benawi/Hello-world/pull/6
image

**Review by AbelG101 — CHANGES_REQUESTED** [review]
## Hi @Benawi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not following the GitHub flow. according to GitHub flow, you should make a pull request from a feature branch into the main or master branch of your repo. and all the required changes and requirements should be on the feature branch so that a reviewer can review them.
- I can see you've created 4 branches which are unnecessary, so please create a new branch from your main and add the changes there and also make sure to provide a link to this PR explaining that you've made a mistake, so the reviewer knows it's not a first time review. Good luck 👍🏾 .

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
